### ISSUE TITLE
Can't compile on RedHat 4.1

### ISSUE THREAD

**Issue by ndmitchell** [haskell-crypto/cryptonite#64]
Using Red Hat 4.1.2-54 x86_64, I have to compile `cryptonite` with `--flag=-support_aesni` (which is reasonable), and then fail with:

```
Last 10 lines of the build log ( /devshared/home/cortexdev/.cabal/logs/cryptonite-0.10.log ):
dist/build/cbits/blake2/sse/blake2bp.dyn_o: In function `fgetc_unlocked':
blake2bp.c:(.text+0xe90): multiple definition of `fgetc_unlocked'
dist/build/cbits/cryptonite_chacha.dyn_o:cryptonite_chacha.c:(.text+0xe60): first defined here
dist/build/cbits/blake2/sse/blake2bp.dyn_o: In function `getchar':
blake2bp.c:(.text+0xeb0): multiple definition of `getchar'
dist/build/cbits/cryptonite_chacha.dyn_o:cryptonite_chacha.c:(.text+0xe80): first defined here
dist/build/cbits/blake2/sse/blake2bp.dyn_o: In function `vprintf':
blake2bp.c:(.text+0xec0): multiple definition of `vprintf'
dist/build/cbits/cryptonite_chacha.dyn_o:cryptonite_chacha.c:(.text+0xe90): first defined here
collect2: ld returned 1 exit status
cabal: Error: some packages failed to install:
cryptonite-0.10 failed during the building phase. The exception was:
```

Would be nice if it worked, although I appreciate this is an ancient system.

**Comment by vincenthz** [comment]
Looks like a bug involving a combinaison of old glibc, old gcc, and c99 / O2 building

one example: https://gforge.inria.fr/tracker/?func=detail&group_id=131&atid=607&aid=14070

The quick workaround is to add `-fgnu89-inline` in the CFLAGS to prevent bad duplicated inline of glibc functions.

one more permanent workaround would be to disable c99, and remove a bunch of forward type definitions in blake2 (e.g. `int` defined in loop that is forbidden in c89). I think blake2 is the only place that requires c99

**Comment by vincenthz** [comment]
@ndmitchell any chance you could retry before I cut a new release, with `old_toolchain_inliner` set ?

**Comment by ndmitchell** [comment]
Sure, probably in a few hours (kick me if I forget)

**Comment by ndmitchell** [comment]
Thanks, this seems to have worked.
