### ISSUE TITLE
Unable to build on MacOS 13.4.1 (aarch64)

### ISSUE THREAD

**Issue by awgn** [haskell-crypto/cryptonite#379]
Unable to build on MacBook with Apple Silicon M2 (MacOS 13.4.1).

I get the following error when using LTS-21.1 build plan, which build the cryptonite 0.30:

```
cryptonite         > /private/var/folders/1y/wlf2x0px78j8t0f77n93w2mh0000gn/T/stack-21ec6fed9d1a094f/cryptonite-0.30//Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/mmintrin.h:14:2: error:
cryptonite         >      error: "This header is only meant to be used on x86 and x64 architecture"
cryptonite         >    |
cryptonite         > 14 | #error "This header is only meant to be used on x86 and x64 architecture"
cryptonite         >    |  ^
cryptonite         > #error "This header is only meant to be used on x86 and x64 architecture"
cryptonite         >  ^
cryptonite         >
cryptonite         > /private/var/folders/1y/wlf2x0px78j8t0f77n93w2mh0000gn/T/stack-21ec6fed9d1a094f/cryptonite-0.30//Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/mmintrin.h:54:12: error:
cryptonite         >      error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
cryptonite         >         return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
cryptonite         >                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cryptonite         >    |
cryptonite         > 54 |     return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
cryptonite         >    |            ^
cryptonite         >
cryptonite         > /private/var/folders/1y/wlf2x0px78j8t0f77n93w2mh0000gn/T/stack-21ec6fed9d1a094f/cryptonite-0.30//Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/mmintrin.h:133:12: error:
cryptonite         >      error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
cryptonite         >         return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
cryptonite         >                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cryptonite         >     |
cryptonite         > 133 |     return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
cryptonite         >     |            ^
cryptonite         >
cryptonite         > /private/var/folders/1y/wlf2x0px78j8t0f77n93w2mh0000gn/T/stack-21ec6fed9d1a094f/cryptonite-0.30//Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/mmintrin.h:163:12: error:
cryptonite         >      error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
cryptonite         >         return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
cryptonite         >                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cryptonite         >     |
cryptonite         > 163 |     return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (__v2si)__m2);
cryptonite         >     |            ^
cryptonite         >
cryptonite         > /private/var/folders/1y/wlf2x0px78j8t0f77n93w2mh0000gn/T/stack-21ec6fed9d1a094f/cryptonite-0.30//Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/mmintrin.h:193:12: error:
cryptonite         >      error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
cryptonite         >         return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
cryptonite         >                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cryptonite         >     |
cryptonite         > 193 |     return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (__v4hi)__m2);
cryptonite         >     |            ^
cryptonite         >
cryptonite         > /private/var/folders/1y/wlf2x0px78j8t0f77n93w2mh0000gn/T/stack-21ec6fed9d1a094f/cryptonite-0.30//Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/mmintrin.h:220:12: error:
cryptonite         >      error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
cryptonite         >         return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
cryptonite         >                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cryptonite         >     |
cryptonite         > 220 |     return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, (__v8qi)__m2);
cryptonite         >     |            ^
cryptonite         >
cryptonite         > /private/var/folders/1y/wlf2x0px78j8t0f77n93w2mh0000gn/T/stack-21ec6fed9d1a094f/cryptonite-0.30//Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/mmintrin.h:243:12: error:
cryptonite         >      error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
cryptonite         >         return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
cryptonite         >                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cryptonite         >     |
cryptonite         > 243 |     return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, (__v4hi)__m2);
cryptonite         >     |            ^
cryptonite         >
cryptonite         > /private/var/folders/1y/wlf2x0px78j8t0f77n93w2mh0000gn/T/stack-21ec6fed9d1a094f/cryptonite-0.30//Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/mmintrin.h:264:12: error:
cryptonite         >      error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
cryptonite         >         return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
cryptonite         >                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cryptonite         >     |
cryptonite         > 264 |     return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, (__v2si)__m2);
cryptonite         >     |            ^
cryptonite         >
cryptonite         > /private/var/folders/1y/wlf2x0px78j8t0f77n93w2mh0000gn/T/stack-21ec6fed9d1a094f/cryptonite-0.30//Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/mmintrin.h:291:12: error:
cryptonite         >      error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
cryptonite         >         return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
cryptonite         >                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cryptonite         >     |
cryptonite         > 291 |     return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, (__v8qi)__m2);
cryptonite         >     |            ^
cryptonite         >
cryptonite         > /private/var/folders/1y/wlf2x0px78j8t0f77n93w2mh0000gn/T/stack-21ec6fed9d1a094f/cryptonite-0.30//Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/mmintrin.h:314:12: error:
cryptonite         >      error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
cryptonite         >         return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
cryptonite         >                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cryptonite         >     |
cryptonite         > 314 |     return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, (__v4hi)__m2);
cryptonite         >     |            ^
cryptonite         >
cryptonite         > /private/var/folders/1y/wlf2x0px78j8t0f77n93w2mh0000gn/T/stack-21ec6fed9d1a094f/cryptonite-0.30//Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/mmintrin.h:335:12: error:
cryptonite         >      error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
cryptonite         >         return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
cryptonite         >                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cryptonite         >     |
cryptonite         > 335 |     return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, (__v2si)__m2);
cryptonite         >     |            ^
cryptonite         >
cryptonite         > /private/var/folders/1y/wlf2x0px78j8t0f77n93w2mh0000gn/T/stack-21ec6fed9d1a094f/cryptonite-0.30//Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/mmintrin.h:356:12: error:
cryptonite         >      error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
cryptonite         >         return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
cryptonite         >                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cryptonite         >     |
cryptonite         > 356 |     return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
cryptonite         >     |            ^
cryptonite         >
cryptonite         > /private/var/folders/1y/wlf2x0px78j8t0f77n93w2mh0000gn/T/stack-21ec6fed9d1a094f/cryptonite-0.30//Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/mmintrin.h:377:12: error:
cryptonite         >      error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
cryptonite         >         return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
cryptonite         >                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cryptonite         >     |
cryptonite         > 377 |     return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
cryptonite         >     |            ^
cryptonite         >
cryptonite         > /private/var/folders/1y/wlf2x0px78j8t0f77n93w2mh0000gn/T/stack-21ec6fed9d1a094f/cryptonite-0.30//Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/mmintrin.h:398:12: error:
cryptonite         >      error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
cryptonite         >         return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
cryptonite         >                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cryptonite         >     |
cryptonite         > 398 |     return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
cryptonite         >     |            ^
cryptonite         >
cryptonite         > /private/var/folders/1y/wlf2x0px78j8t0f77n93w2mh0000gn/T/stack-21ec6fed9d1a094f/cryptonite-0.30//Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/mmintrin.h:420:12: error:
cryptonite         >      error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
cryptonite         >         return (__m64)__builtin_ia32_paddsb((__v8qi)__m1, (__v8qi)__m2);
cryptonite         >                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cryptonite         >     |
cryptonite         > 420 |     return (__m64)__builtin_ia32_paddsb((__v8qi)__m1, (__v8qi)__m2);
cryptonite         >     |            ^
cryptonite         >
cryptonite         > /private/var/folders/1y/wlf2x0px78j8t0f77n93w2mh0000gn/T/stack-21ec6fed9d1a094f/cryptonite-0.30//Library/Developer/CommandLineTools/usr/lib/clang/14.0.3/include/mmintrin.h:443:12: error:
cryptonite         >      error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
cryptonite         >         return (__m64)__builtin_ia32_paddsw((__v4hi)__m1, (__v4hi)__m2);
cryptonite         >                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cryptonite         >     |
cryptonite         > 443 |     return (__m64)__builtin_ia32_paddsw((__v4hi)__m1, (__v4hi)__m2);
cryptonite         >     |            ^
cryptonite         > fatal error: too many errors emitted, stopping now [-ferror-limit=]
cryptonite         > 20 errors generated.
cryptonite         > `gcc' failed in phase `C Compiler'. (Exit code: 1)
Progress 5/34

Error: [S-7282]
       Stack failed to execute the build plan.

       While executing the build plan, Stack encountered the following errors:

       [S-7011]
       While building package cryptonite-0.30 (scroll up to its section to see the error) using:
       /Users/nicola/.stack/setup-exe-cache/aarch64-osx/Cabal-simple_6HauvNHV_3.8.1.0_ghc-9.4.5 --verbose=1 --builddir=.stack-work/dist/aarch64-osx/Cabal-3.8.1.0 build --ghc-options " -fdiagnostics-color=always"
       Process exited with code: ExitFailure 1
```

```
$ gcc --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Any workaround?

**Comment by awgn** [comment]
I didn't notice stack script was enabling the SIMD support, which is not available in arm arch.
